### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by enbge** [FrozenQueenElsa0903/Elsa-Owo-Selfbot-ver-Full#8]
What can i do?
![bat6gn4](https://user-images.githubusercontent.com/90988241/193694488-95d2945e-cea9-4a02-8a0b-5c4f1bbec802.png)

**Comment by Frozen-Queen-Elsa** [comment]
type window+R , after that type %appdata% .
At this path
AppData\Local\Programs\Python\Python38\Lib\site-packages\discum\gateway.
go this https://github.com/ericz/Discord-S.C.U.M/tree/master/discum/gateway 
and download type.py
copy to previous path

**Comment by gzlrn** [comment]
it still the same..
